version: '3.4'

services:
  configurationserver:
    image: ${DOCKER_REGISTRY-}configurationserver
    build:
      context: .
      dockerfile: ConfigurationServer/Dockerfile

  clientrestserver:
    image: ${DOCKER_REGISTRY-}clientrestserver
    build:
      context: .
      dockerfile: ClientRestServer/Dockerfile
